apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw.fullname" . }}-config-files
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
data:
  HEARTBEAT.md: |
{{ .Values.configFiles.heartbeat | indent 4 }}
  openclaw.json: |
{{ .Values.configFiles.openclawJson | indent 4 }}
